#!/usr/bin/env python
#-*- coding: utf-8 -*-

import tile_info

#GLOBAL VARS
MAP_TILES = []
CANVAS_WIDTH = 100
CANVAS_HEIGHT = 100
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 900
MAIN_WINDOW_PROPORTION = 0.75

GROUP_LIST = []

REFRESH_FREQ = 20
FORCED_FPS = 30

GEN_ONLY = False

DEFAULT_DRAWING = True
BIOME = tile_info.LANDSCAPE_ISLANDS
COLOR_PALETTE = BIOME.keys()
COLOR_PROBA   = BIOME.values()
# COLOR_PROBA   = None

FAST_DISPLAY = False

EIGHT_NEIGHBOURS = True