#!/usr/bin/env python
#-*- coding: utf-8 -*-

import tile_info

#GLOBAL VARS
MAP_TILES = []
CANVAS_WIDTH = 100
CANVAS_HEIGHT = 100
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700

REFRESH_FREQ = 20
FORCED_FPS = 30

COLOR_PALETTE = tile_info.LANDSCAPE_ISLANDS.keys()
# COLOR_PROBA   = tile_info.LANDSCAPE_ISLANDS.values()
COLOR_PROBA   = None

EIGHT_NEIGHBOURS = True