#!/usr/bin/env python
#-*- coding: utf-8 -*-

import tile_info

#GLOBAL VARS
MAP_TILES              = []
CANVAS_WIDTH           = 100
CANVAS_HEIGHT          = 100
WINDOW_WIDTH           = 1200
WINDOW_HEIGHT          = 700
MAIN_WINDOW_PROPORTION = 0.75

CARAVAN_LIST        = []
STARTING_NB_CARAVAN = 5
MIN_POP_PER_CARAVAN = 150.0
MAX_POP_PER_CARAVAN = 600.0

VILLAGE_LIST = []
TOWN_LIST    = []
CITY_LIST    = []

RIVERS = []

MIN_TILE_SCORE = 0.0
MAX_TILE_SCORE = 0.0

REFRESH_FREQ = 20
FORCED_FPS   = 30

GEN_ONLY = False

DEFAULT_DRAWING = False
# BIOME = tile_info.LANDSCAPE_TEST
BIOME = tile_info.LANDSCAPE_DEFAULT
# BIOME = tile_info.LANDSCAPE_ISLANDS
# BIOME = tile_info.LANDSCAPE_MOUNTAINS
if not DEFAULT_DRAWING:
	COLOR_PALETTE = BIOME.keys()
	COLOR_PROBA   = BIOME.values()
else:
	COLOR_PALETTE = tile_info.LANDSCAPE_COLOR_LIST 
# COLOR_PROBA   = None

FAST_DISPLAY = False

EIGHT_NEIGHBOURS = True

HEATMAP_TYPE = 0